# Settings for the Makefile which define
# various things like the names, paths, etc pp
# 

# GRF Name
GRF_NAME     = OpenGFX
GRF_VERSION  = 0.1.0 - beta 5
FILENAMES    = ogfx1 ogfxc ogfxh ogfxi ogfxt ogfxe 

# Build parameters and programmes
NFORENUM_FLAGS = -w 141
GRFCODEC_FLAGS = -e -p 2

NFORENUM = renum
GRFCODEC = grfcodec

# Paths defining the directory layout
SPRITEDIR   = ./sprites
DOCDIR      = ./doc
NFODIR      = $(SPRITEDIR)/nfo

MAINDIRS    = $(SPRITEDIR) $(DOCDIR)
