# This file defines the principal settings for this project

# Definition of the grfs
REPO_NAME           ?= OpenGFX
REPO_SHORTNAME     := OGFX
REPO_PALETTE        = DOS
REPO_BLITTER        = 8bpp
REPO_ORIGIN         = default = Please redownload from official source.

BUNDLE_FILES        ?= $(GRF_FILES) $(DOC_FILES) opengfx.obg

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= ogfx1_base ogfxc_arctic ogfxh_tropical ogfxt_toyland ogfxi_logos ogfxe_extra
PROJECT_FILENAME    ?= opengfx

# Documentation files
DOC_FILES ?= docs/readme.txt docs/license.txt docs/changelog.txt

# Possible offset to NewGRF version. Increase by one, if a release
# branch is added to the repository
REPO_BRANCH_VERSION ?= 0

# Directory structure
SCRIPT_DIR          ?= scripts
DESC_FILENAME_SRC      := docs/descriptions.ptxt

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
GFX_SCRIPT_LIST_FILES      := sprites/png/terrain/waterfeatures/waterfeatures.xcf2png sprites/png/infrastructure/locks.xcf2png sprites/png/terrain/terrain.xcf2png sprites/png/trees/trees.xcf2png sprites/png/industries/coalmine.xcf2png sprites/png/industries/goldmine/goldmine.xcf2png sprites/png/industries/oilwell/oilwell.xcf2png

# If needed, declare the minimum NML requirements
# REQUIRED_NML_BRANCH  = 0.3
# MIN_NML_REVISION     = 0

# OpenTTD GUI sprites were added in NML r2049. We need 0.3 branch.
NML_MIN_VERSION  := 030
NML_MIN_REVISION := 2049
